using Volo.Abp;

namespace PermissionControlSystem.EntityFrameworkCore;

public abstract class PermissionControlSystemEntityFrameworkCoreTestBase : PermissionControlSystemTestBase<PermissionControlSystemEntityFrameworkCoreTestModule>
{

}
