using PermissionControlSystem.EntityFrameworkCore;
using Xunit;

namespace PermissionControlSystem.EntityFrameworkCore;

public class PermissionControlSystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<PermissionControlSystemEntityFrameworkCoreFixture>
{

}
